test: new code coverage check

diff --git a/util/hooks/pre-commit b/util/hooks/pre-commit
--- a/util/hooks/pre-commit
+++ b/util/hooks/pre-commit
@@ -68,3 +68,9 @@ then
     echo "Tests failed"
     exit 1
 fi
+
+if ! make coverage
+then
+    echo "Code coverage check failed"
+    exit 1
+fi
